### ISSUE TITLE
python3运行之后出错。

### ISSUE THREAD

**Issue by Hope-you** [ZainCheung/netease-cloud-api#19]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 1182, in run
    self.function(*self.args, **self.kwargs)
  File "/home/下载/wangyi/netease-cloud/main.py", line 247, in taskPool
    config = init()
  File "/home/下载/wangyi/netease-cloud/main.py", line 192, in init
    uin = config['token']['account']
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'token'

请问一下，这个问题出在哪里呢？api测试是可以使用的。账号密码也都是对的。

**Comment by Hope-you** [comment]
解决了，是配置文件的问题，可能输入了一些看不见的字符，删除原来的配置文件，再新建一个配置文件就行了。

**Comment by Hope-you** [comment]
解决了，是配置文件的问题，可能输入了一些看不见的字符，删除原来的配置文件，再新建一个配置文件就行了。
